name: Build IconGrabber

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkita64:latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          make

      - name: Upload NRO
        uses: actions/upload-artifact@v4
        with:
          name: IconGrabber-nro
          path: "*.nro"
